// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpFyYEegDI3AvZ1Sy8tqTtemB1Rc7r44M',
    appId: '1:960603308978:web:12f4ef74fbd6abb6149aab',
    messagingSenderId: '960603308978',
    projectId: 'vibz-c4aff',
    authDomain: 'vibz-c4aff.firebaseapp.com',
    storageBucket: 'vibz-c4aff.firebasestorage.app',
    measurementId: 'G-ZG4R6ZT0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtknvt3lvptGaAUJFqYifPMtP9WeLNa1w',
    appId: '1:960603308978:android:6234898e2a1667d0149aab',
    messagingSenderId: '960603308978',
    projectId: 'vibz-c4aff',
    storageBucket: 'vibz-c4aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPFLKpiyoiseAmWTidtKJZnJZ2A6jBE0',
    appId: '1:960603308978:ios:0d809942ceb41711149aab',
    messagingSenderId: '960603308978',
    projectId: 'vibz-c4aff',
    storageBucket: 'vibz-c4aff.firebasestorage.app',
    iosBundleId: 'com.example.vibz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlPFLKpiyoiseAmWTidtKJZnJZ2A6jBE0',
    appId: '1:960603308978:ios:0d809942ceb41711149aab',
    messagingSenderId: '960603308978',
    projectId: 'vibz-c4aff',
    storageBucket: 'vibz-c4aff.firebasestorage.app',
    iosBundleId: 'com.example.vibz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpFyYEegDI3AvZ1Sy8tqTtemB1Rc7r44M',
    appId: '1:960603308978:web:115a4403ccb48c80149aab',
    messagingSenderId: '960603308978',
    projectId: 'vibz-c4aff',
    authDomain: 'vibz-c4aff.firebaseapp.com',
    storageBucket: 'vibz-c4aff.firebasestorage.app',
    measurementId: 'G-MKSQDK5RR8',
  );
}
